<?xml version="1.0" encoding="utf-8"?><Database Name="ptc" Class="db_ptcDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=daenerys-one.database.windows.net;Initial Catalog=ptc;Persist Security Info=True;User ID=ptcadmin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ptcConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Client">
      <Column Name="ClientId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClientContactid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClientActiveDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ClientInactiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ClientLogo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ClientActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ClientName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ClientAddressLine1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ClientAddressLine2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ClientAddressCity" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientAddressState" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientAddressZip" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="ClientNotes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Client_Property" Member="Properties" ThisKey="ClientId" OtherKey="PropertyClientId" Type="Property" />
      <Association Name="Contact_Client" Member="Contact" ThisKey="ClientContactid" OtherKey="Contactid" Type="Contact" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Properties" Member="Properties">
    <Type Name="Property">
      <Column Name="PropertyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyClientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PropertyContactid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PropertyName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InternalCode" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyCounty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyIsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PropertyActiviatedDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PropertyInactivatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PropertyAddressLine1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyAddressLine2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PropertyAddressCity" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyAddressState" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyAddressZip" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyPrimaryUse" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyCharYearBuilt" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="PropertyCharUnits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PropertyCharGBA" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PropertyCharNLA" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PropertyInfoSalesPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PropertyInfoSalesDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PropertyFlagIncomeProducing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PropertyFlagIEReceived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PropertyFlagRRReceived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PropertyFlagAOAReceived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PropertyAOAExpDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Property_Parcel" Member="Parcels" ThisKey="PropertyId" OtherKey="ParcelPropertyId" Type="Parcel" />
      <Association Name="Client_Property" Member="Client" ThisKey="PropertyClientId" OtherKey="ClientId" Type="Client" IsForeignKey="true" />
      <Association Name="Contact_Property" Member="Contact" ThisKey="PropertyContactid" OtherKey="Contactid" Type="Contact" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Parcel" Member="Parcels">
    <Type Name="Parcel">
      <Column Name="ParcelId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParcelPropertyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParcelFlagActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ParcelActiveDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ParcelInactiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ParcelPropId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParcelGeoId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParcelDBA" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ParcelSitusStreetprefx" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParcelSitusStreet" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParcelSitusStreetSuffix" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ParcelSitusCity" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ParcelSitusZip" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="ParcelLegalDesc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ParcelOwnerName" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="ParcelOwnerAddressLine1" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="ParcelOwnerAddressLine2" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="ParcelOwnerAddressCity" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParcelOwnerAddressState" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParcelOwnerAddressZip" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="ParcelCharGBA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParcelCharNLA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParcelCharYearBuilt" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="ParcelNotes" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ParcelAppraisalAuthoritiesId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Parcel_ProcessYear" Member="ProcessYears" ThisKey="ParcelId" OtherKey="ProcessYearsParcelsId" Type="ProcessYear" />
      <Association Name="Property_Parcel" Member="Property" ThisKey="ParcelPropertyId" OtherKey="PropertyId" Type="Property" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contacts" Member="Contacts">
    <Type Name="Contact">
      <Column Name="Contactid" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContactSalutation" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ContactFirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactLastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactAddressLine1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactAddressLine2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactAddressCity" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactAddressState" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactAddressZip" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="ContactEmailAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactAltEmailAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactBusinessNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ContactBusinessNumberExtension" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactCellularNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ContactFaxNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Contact_Client" Member="Clients" ThisKey="Contactid" OtherKey="ClientContactid" Type="Client" />
      <Association Name="Contact_Property" Member="Properties" ThisKey="Contactid" OtherKey="PropertyContactid" Type="Property" />
    </Type>
  </Table>
  <Table Name="dbo.HearingSchedule" Member="HearingSchedules">
    <Type Name="HearingSchedule">
      <Column Name="HearingScheduleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HearingScheduleInformalHearingDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="HearingScheduleInformalHearingTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="HearingScheduleFormalHearingDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="HearingScheduleFormalHearingTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="HearingScheduleLitigationDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HearingScheduleLitigationTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="HearingSchedulePrevFormalHearingDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HearingSchedulePostmarkDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HearingScheduleRescheduleStatus" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="HearingScheduleRescheduledRequestDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HearingScheduleBoardOrderRecdDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="HearingSchedule_ProcessYear" Member="ProcessYears" ThisKey="HearingScheduleId" OtherKey="HearingSchedule_HearingScheduleId" Type="ProcessYear" />
    </Type>
  </Table>
  <Table Name="dbo.ProcessYears" Member="ProcessYears">
    <Type Name="ProcessYear">
      <Column Name="ProcessYearId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProcessYearsParcelsId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProcessYear" Member="ProcessYear1" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="ProcessYearProposedLandValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessYearProposedImpValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessYearProposedTotalValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessYearCurrentStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessYearStatusChangeDate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessYearARBLandValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessYearARBImpValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessYearARBTotalValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessYearLitLandValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessYearLitImpValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessYearLitTotalValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessYearAppealDeadline" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ProcessYearNotes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ProcessYearChangedBy" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="HearingSchedule_HearingScheduleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HearingSchedule_ProcessYear" Member="HearingSchedule" ThisKey="HearingSchedule_HearingScheduleId" OtherKey="HearingScheduleId" Type="HearingSchedule" IsForeignKey="true" />
      <Association Name="Parcel_ProcessYear" Member="Parcel" ThisKey="ProcessYearsParcelsId" OtherKey="ParcelId" Type="Parcel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SearchAppraisalDistrictData" Member="SearchAppraisalDistrictDatas">
    <Type Name="SearchAppraisalDistrictData">
      <Column Name="initial_dataloadid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="current_dataloadid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="prop_county" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="prop_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="prop_type_cd" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="prop_val_yr" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="geo_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="py_owner_name" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="py_addr_line1" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="py_addr_line2" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="py_addr_line3" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="py_addr_city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="py_addr_state" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="py_addr_country" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="py_addr_zip" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="py_addr_zip_cass" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="situs_street" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="legal_desc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="abs_subdv_cd" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="abs_subdv_desc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="hood_cd" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="land_acres" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
      <Column Name="year_built" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="effective_year_built" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="prop_use_cd" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="prop_use_desc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="class" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="gross_building_area" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="net_rentable_area" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="property_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="proposed_land_hstd_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="proposed_land_non_hstd_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="proposed_imprv_hstd_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="proposed_imprv_non_hstd_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="proposed_ag_use_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="proposed_ag_market" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="proposed_timber_use" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="proposed_timber_market" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="proposed_appraised_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="proposed_ten_percent_cap" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="proposed_assessed_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="proposed_market_value" Type="System.Decimal" DbType="Decimal(14,0)" CanBeNull="true" />
      <Column Name="current_land_hstd_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="current_land_non_hstd_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="current_imprv_hstd_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="current_imprv_non_hstd_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="current_ag_use_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="current_ag_market" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="current_timber_use" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="current_timber_market" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="current_appraised_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="current_ten_percent_cap" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="current_assessed_val" Type="System.Decimal" DbType="Decimal(15,0)" CanBeNull="true" />
      <Column Name="current_market_value" Type="System.Decimal" DbType="Decimal(14,0)" CanBeNull="true" />
      <Column Name="exemptions" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SearchTaxOfficeData" Member="SearchTaxOfficeDatas">
    <Type Name="SearchTaxOfficeData">
      <Column Name="DATALOADID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COUNTY" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ACCOUNT" Type="System.String" DbType="VarChar(34)" CanBeNull="true" />
      <Column Name="sYEAR" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="JURISDICTION" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="TAXUNITACCT" Type="System.String" DbType="VarChar(34)" CanBeNull="true" />
      <Column Name="LEVY" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EXPHOMESTEAD" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="EXPOVER65" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="EXPVETERAN" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="EXPDISABLED" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="EXPAG" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DATEPAID" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="DUEDATE" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="OMITFLAG" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="LEVYBALANCE" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="SUIT" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CAUSENO" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="BANKCODE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="BANKRUPTNO" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ATTORNEY" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="COURTCOST" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="ABSTRACTFEE" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="DEFERRAL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="BILLSUPP" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SPLITPMTFLAG" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CATAGORYCODE" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="ACCTOWNER" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ACCTADDRESS2" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ACCTADDRESS3" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ACCTADDRESS4" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ACCTCITY" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ACCTSTATE" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ZIP" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="ROLLCODE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PARCELNO" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PARCELNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PAYMENTAGREEMENT" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TOTAMTDUE" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="TOTAMTDUE30" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="TOTAMTDUE60" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="TOTAMTDUE90" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="AMOUNTINDICATOR" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.NewClientSetup" Method="NewClientSetup">
    <Parameter Name="ClientContactId" Parameter="clientContactId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClientActiveDate" Parameter="clientActiveDate" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="ClientLogo" Parameter="clientLogo" Type="System.Data.Linq.Binary" DbType="VarBinary(1)" />
    <Parameter Name="ClientActive" Parameter="clientActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Clientname" Parameter="clientname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ClientAddressLine1" Parameter="clientAddressLine1" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ClientAddressLine2" Parameter="clientAddressLine2" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ClientAddressCity" Parameter="clientAddressCity" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ClientAddressState" Parameter="clientAddressState" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ClientAddressZip" Parameter="clientAddressZip" Type="System.String" DbType="Char(5)" />
    <Parameter Name="ClientNotes" Parameter="clientNotes" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="PropertyContactid" Parameter="propertyContactid" Type="System.Int32" DbType="Int" />
    <Parameter Name="PropertyName" Parameter="propertyName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="InternalCode" Parameter="internalCode" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="PropertyCounty" Parameter="propertyCounty" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PropertyIsActive" Parameter="propertyIsActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PropertyActiviatedDate" Parameter="propertyActiviatedDate" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="PropertyAddressLine1" Parameter="propertyAddressLine1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PropertyAddressLine2" Parameter="propertyAddressLine2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PropertyAddressCity" Parameter="propertyAddressCity" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PropertyAddressState" Parameter="propertyAddressState" Type="System.String" DbType="Char(2)" />
    <Parameter Name="PropertyAddressZip" Parameter="propertyAddressZip" Type="System.String" DbType="Char(5)" />
    <Parameter Name="PropertyPrimaryUse" Parameter="propertyPrimaryUse" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="PropertyCharYearBuilt" Parameter="propertyCharYearBuilt" Type="System.String" DbType="Char(4)" />
    <Parameter Name="PropertyCharUnits" Parameter="propertyCharUnits" Type="System.Int32" DbType="Int" />
    <Parameter Name="PropertyCharGBA" Parameter="propertyCharGBA" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="PropertyCharNLA" Parameter="propertyCharNLA" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="PropertyInfoSalesPrice" Parameter="propertyInfoSalesPrice" Type="System.Decimal" DbType="Money" />
    <Parameter Name="PropertyInfoSalesDate" Parameter="propertyInfoSalesDate" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="PropertyFlagIncomeProducing" Parameter="propertyFlagIncomeProducing" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PropertyFlagIEReceived" Parameter="propertyFlagIEReceived" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PropertyFlagRRReceived" Parameter="propertyFlagRRReceived" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PropertyFlagAOAReceived" Parameter="propertyFlagAOAReceived" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PropertyAOAExpDate" Parameter="propertyAOAExpDate" Type="System.DateTime" DbType="SmallDateTime" />
    <Return Type="System.Int32" />
  </Function>
</Database>